const DATA_FILES=['ingredients','recipes','menu','inventory','shopping-plans','products','settings','utilization'];
const STORAGE_KEY='mesa21_state_v1';
const navItems=[
 ['inicio','⌂','Inicio'],['hoy','✓','Hoy'],['calendario','▦','Calendario 21 días'],['recetas','◇','Recetas'],
 ['inventario','▤','Inventario'],['frio','❄','Nevera y congelador'],['compra','◉','Próxima compra'],
 ['compras','☷','Todas las compras'],['aprovechamiento','↗','Aprovechamiento'],['configuracion','⚙','Configuración']
];
const mealStatuses={pending:'Pendiente',preparing:'Preparando',prepared:'Preparada',consumed:'Consumida',skipped:'Omitida',substituted:'Sustituida'};
let db={},state={},route='inicio',filters={recipe:'',category:'todas',inventory:'todas'};
const $=s=>document.querySelector(s); const app=$('#app');
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=v=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(Number(v)||0);
const title=s=>s?String(s).replaceAll('_',' ').replace(/^./,c=>c.toUpperCase()):'';
const byId=(key,id)=>db[key]?.find(x=>x.id===id);
const recipe=id=>byId('recipes',id);
const ingredient=id=>byId('ingredients',id);
const recipeNames=ids=>ids.map(id=>recipe(id)?.name||id).join(' + ');

async function init(){
  try{
    const loaded=await Promise.all(DATA_FILES.map(async name=>{const r=await fetch(`data/${name}.json`);if(!r.ok)throw new Error(`${name}: ${r.status}`);return [name,await r.json()]}));
    const raw=Object.fromEntries(loaded);
    db={ingredients:raw.ingredients.ingredients,recipes:raw.recipes.recipes,days:raw.menu.days,initialInventory:raw.inventory.items,shopping:raw['shopping-plans'].plans,products:raw.products.products,productUpdated:raw.products.last_updated,settings:raw.settings,flows:raw.utilization.flows};
    loadState(); renderNav(); handleRoute(); bindGlobal();
  }catch(err){app.innerHTML=`<div class="card"><h2>No se pudieron cargar los datos</h2><p>Abre la aplicación mediante GitHub Pages o un servidor local; el navegador no permite cargar JSON desde <span class="mono">file://</span>.</p><p class="mono">${esc(err.message)}</p></div>`}
}
function initialState(){return {schema_version:1,started_at:new Date().toISOString(),settings:{plan_start_date:db.settings.plan_start_date,postal_code:db.settings.postal_code,auto_price_refresh:true,remote_price_feed_url:''},meal_statuses:{},meal_replacements:{},inventory:structuredClone(db.initialInventory),prepared_food:[],shopping_checks:{},purchased_items:[],price_overrides:{},last_remote_price_refresh:null};}
function loadState(){try{state=JSON.parse(localStorage.getItem(STORAGE_KEY))||initialState()}catch{state=initialState()}migrateState()}
function migrateState(){const fresh=initialState();for(const [k,v] of Object.entries(fresh))if(state[k]===undefined)state[k]=v;save(false)}
function save(notify=true){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));const el=$('#save-status');if(el)el.textContent=`Guardado ${new Date().toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'})}`;if(notify)toast('Cambios guardados')}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2200)}
function renderNav(){
  $('#main-nav').innerHTML=navItems.map(([id,icon,label])=>`<a class="nav-link" data-route="${id}" href="#/${id}"><span class="nav-icon">${icon}</span>${label}</a>`).join('');
}
function bindGlobal(){
  window.addEventListener('hashchange',handleRoute);$('#mobile-menu').addEventListener('click',()=>{$('.sidebar').classList.toggle('open');$('#mobile-menu').setAttribute('aria-expanded',$('.sidebar').classList.contains('open'))});
  $('#main-nav').addEventListener('click',()=>$('.sidebar').classList.remove('open'));
  $('#meal-dialog').addEventListener('click',e=>{if(e.target.id==='meal-dialog')e.target.close()});
  $('#import-file').addEventListener('change',importState);
}
function handleRoute(){route=(location.hash.replace('#/','')||'inicio').split('?')[0];if(!navItems.some(x=>x[0]===route))route='inicio';document.querySelectorAll('.nav-link').forEach(a=>a.classList.toggle('active',a.dataset.route===route));render();app.focus({preventScroll:true});window.scrollTo(0,0)}
function render(){const views={inicio:renderHome,hoy:renderToday,calendario:renderCalendar,recetas:renderRecipes,inventario:renderInventory,frio:renderCold,compra:renderNextShopping,compras:renderAllShopping,aprovechamiento:renderFlows,configuracion:renderSettings};app.innerHTML=views[route]();bindView();if(route==='compra'&&state.settings.auto_price_refresh)refreshRemotePrices(true)}
function head(eyebrow,h1,p='',actions=''){return `<header class="page-head"><div><span class="eyebrow">${eyebrow}</span><h1>${h1}</h1>${p?`<p>${p}</p>`:''}</div>${actions?`<div class="head-actions">${actions}</div>`:''}</header>`}
function planDayIndex(){const start=new Date(`${state.settings.plan_start_date}T12:00:00`),now=new Date();return Math.max(0,Math.min(20,Math.floor((new Date(now.getFullYear(),now.getMonth(),now.getDate(),12)-start)/86400000)))}
function currentDay(){return db.days[planDayIndex()]}
function mealStatus(meal){return state.meal_statuses[meal.id]||meal.status||'pending'}
function effectiveRecipeIds(meal){return state.meal_replacements[meal.id]?.recipe_ids||meal.recipe_ids}
function mealName(meal){return state.meal_replacements[meal.id]?.label||meal.display_name||recipeNames(effectiveRecipeIds(meal))}
function dateForDay(day){const d=new Date(`${state.settings.plan_start_date}T12:00:00`);d.setDate(d.getDate()+day.date_offset_days);return d}
function dateLabel(day,long=false){return dateForDay(day).toLocaleDateString('es-ES',long?{weekday:'long',day:'numeric',month:'long'}:{day:'numeric',month:'short'})}
function renderHome(){const d=currentDay(),next=nextShoppingPlan(),low=lowStock().slice(0,4),priority=priorityFoods().slice(0,4);return `${head('Tu centro de operaciones',`Hola, esto es lo de hoy`,`Día ${d.day_number} de 21 · ${dateLabel(d,true)}`)}
  <section class="hero-today"><article class="card soft-green hero-meals"><span class="date-pill">● ${esc(d.weekday)} · semana ${d.week}</span><div class="meal-list">${Object.values(d.meals).map(m=>`<div class="meal-mini"><span>${m.label}</span><strong>${esc(mealName(m))}</strong></div>`).join('')}</div></article><article class="card soft-peach"><span class="eyebrow">Trabajo activo</span><div class="work-number">${d.active_time_minutes}<small> min</small></div><p>${d.total_time_minutes} min totales, con tiempos que pueden solaparse.</p><a class="btn small" href="#/hoy">Organizar cocina →</a></article></section>
  <div class="grid grid-3"><article class="card action-card"><span class="action-icon">❄</span><div><strong>Qué sacar</strong><small>${d.thaw_items.length?d.thaw_items.map(title).join(', '):'Nada previsto hoy'}</small></div></article><article class="card action-card"><span class="action-icon">↗</span><div><strong>Qué sobrará</strong><small>${d.leftover_outputs.length?d.leftover_outputs.map(outputName).join(', '):'Sin reservas planificadas'}</small></div></article><article class="card action-card"><span class="action-icon">◉</span><div><strong>Próxima compra</strong><small>${next?`${next.label} · ${shoppingProgress(next)}% listo`:'Plan completado'}</small></div></article></div>
  <div class="grid grid-2"><section><div class="section-title"><h2>Consumir primero</h2><a href="#/frio">Ver todo</a></div><article class="card"><div class="priority-list">${priority.length?priority.map(foodRow).join(''):`<div class="empty">Aún no hay comida preparada. Aparecerá al marcar recetas como preparadas.</div>`}</div></article></section><section><div class="section-title"><h2>Stock que vigilar</h2><a href="#/inventario">Inventario</a></div><article class="card"><div class="priority-list">${low.length?low.map(stockRow).join(''):`<div class="empty">No hay existencias bajo mínimo.</div>`}</div></article></section></div>`}
function outputName(id){for(const r of db.recipes){const o=r.leftover_outputs.find(x=>x.output_id===id);if(o)return o.name}return title(id)}
function foodRow(f){const days=daysUntil(f.target_consumption_date);return `<div class="priority-item"><span class="action-icon">${f.location==='congelador'?'❄':'◷'}</span><div class="grow"><strong>${esc(f.name)}</strong><span>${f.remaining_servings} ración${f.remaining_servings===1?'':'es'} · ${esc(f.location)}</span></div><span class="badge ${days<=1?'danger':days<=3?'warn':''}">${days<0?'vencido':days===0?'hoy':`${days} d`}</span></div>`}
function stockRow(i){const ing=ingredient(i.ingredient_id);return `<div class="priority-item"><div class="grow"><strong>${esc(ing?.name)}</strong><span>${i.quantity} ${esc(i.unit)} · mínimo ${i.minimum_stock}</span></div><span class="badge danger">reponer</span></div>`}
function lowStock(){return state.inventory.filter(i=>Number(i.quantity)<=Number(i.minimum_stock)).sort((a,b)=>(a.quantity/a.minimum_stock)-(b.quantity/b.minimum_stock))}
function priorityFoods(){return [...state.prepared_food].filter(f=>f.remaining_servings>0).sort((a,b)=>String(a.target_consumption_date).localeCompare(String(b.target_consumption_date)))}
function daysUntil(date){if(!date)return 99;return Math.ceil((new Date(`${date}T12:00:00`)-new Date())/86400000)}

function renderToday(){const d=currentDay(),tasks=timelineTasks(d);return `${head('Cocina coordinada','Qué tengo que hacer hoy',`${dateLabel(d,true)} · ${d.active_time_minutes} min activos · ${d.total_time_minutes} min totales`,`<button class="btn secondary" data-action="print">Imprimir</button>`)}
  <div class="grid grid-2"><section class="card soft-green"><span class="eyebrow">Menú</span>${Object.values(d.meals).map(m=>mealControl(d,m)).join('')}</section><section class="card"><span class="eyebrow">Preparación y aprovechamiento</span><h2>${d.preparations.length?'Plan del día':'Día ligero'}</h2><div class="priority-list">${d.preparations.map(x=>`<div class="priority-item"><span class="action-icon">✓</span><div class="grow"><strong>${esc(x)}</strong></div></div>`).join('')}</div>${d.leftover_outputs.length?`<p><span class="badge">Se generan ${d.leftover_outputs.length} reservas</span></p>`:''}</section></div>
  <div class="section-title"><h2>Sesión sugerida</h2><span class="muted">Inicio orientativo · 18:00</span></div><article class="card"><div class="timeline">${tasks.map(t=>`<div class="timeline-item"><div class="timeline-time">${t.time}</div><span class="timeline-dot"></span><div class="timeline-task"><strong>${esc(t.task)}</strong><span>${esc(t.detail)}</span></div></div>`).join('')}</div></article>`}
function mealControl(day,meal){const s=mealStatus(meal);return `<div class="priority-item"><div class="grow"><span class="eyebrow" style="margin:0">${meal.label} · ${meal.servings} r.</span><strong>${esc(mealName(meal))}</strong><span>${meal.source==='leftover'?'Usa una reserva':'Preparación planificada'}</span></div><select class="search meal-status" data-day="${day.id}" data-meal="${meal.id}" style="min-width:135px"><option value="pending" ${s==='pending'?'selected':''}>Pendiente</option><option value="preparing" ${s==='preparing'?'selected':''}>Preparando</option><option value="prepared" ${s==='prepared'?'selected':''}>Preparada</option><option value="consumed" ${s==='consumed'?'selected':''}>Consumida</option><option value="skipped" ${s==='skipped'?'selected':''}>Omitida</option><option value="substituted" ${s==='substituted'?'selected':''}>Sustituida</option></select><button class="btn ghost small" data-action="edit-meal" data-day="${day.id}" data-meal="${meal.id}">Cambiar</button></div>`}
function timelineTasks(d){const rs=Object.values(d.meals).flatMap(m=>effectiveRecipeIds(m)).map(recipe).filter(Boolean).filter(r=>r.category!=='desayuno');let min=0;const tasks=[];for(const r of rs){const equipment=r.equipment.join(', ');r.steps.forEach((step,i)=>{tasks.push({time:addMinutes('18:00',min),task:step,detail:`${r.name} · ${equipment}`});min+=i===0?Math.min(10,Math.ceil(r.active_time_minutes/r.steps.length)):Math.min(15,Math.ceil(r.active_time_minutes/r.steps.length))});}return tasks.sort((a,b)=>a.time.localeCompare(b.time)).slice(0,9)}
function addMinutes(base,min){const [h,m]=base.split(':').map(Number),d=new Date(2000,0,1,h,m+min);return d.toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'})}

function renderCalendar(){return `${head('Plan flexible','Calendario de 21 días','Pulsa cualquier comida para ver detalles, cambiarla o actualizar su estado.')} ${[1,2,3].map(w=>`<section class="week-block"><h2 class="week-label">Semana ${w}</h2><div class="calendar-grid">${db.days.filter(d=>d.week===w).map(dayCard).join('')}</div></section>`).join('')}`}
function dayCard(d){const isToday=d.id===currentDay().id;return `<article class="day-card ${isToday?'today':''}"><span class="day-num">${dateForDay(d).getDate()}</span><span class="weekday">${d.weekday} · ${dateLabel(d)}</span>${Object.values(d.meals).map(m=>`<div class="day-meal"><small>${m.label}</small><button data-action="edit-meal" data-day="${d.id}" data-meal="${m.id}">${esc(mealName(m))}</button></div>`).join('')}<div class="day-meta"><span class="badge">${d.active_time_minutes} min activos</span>${d.leftover_outputs.length?`<span class="badge warn">${d.leftover_outputs.length} sobras</span>`:''}</div></article>`}

function renderRecipes(){const cats=['todas',...new Set(db.recipes.map(r=>r.category))],shown=db.recipes.filter(r=>(filters.category==='todas'||r.category===filters.category)&&(`${r.name} ${r.source_code} ${r.tags.join(' ')}`.toLowerCase().includes(filters.recipe.toLowerCase())));return `${head('Recetario normalizado','Recetas',`${db.recipes.length} recetas y bases enlazadas a ingredientes canónicos.`)}<div class="toolbar"><input id="recipe-search" class="search" type="search" value="${esc(filters.recipe)}" placeholder="Buscar receta o código…"><select id="recipe-category" class="search">${cats.map(c=>`<option value="${c}" ${filters.category===c?'selected':''}>${title(c)}</option>`).join('')}</select></div><div class="grid grid-4">${shown.map(recipeCard).join('')}</div>`}
function recipeCard(r){return `<article class="card recipe-card"><div class="recipe-top"><span class="recipe-code">${r.source_code}</span><span class="badge ${r.time_confidence==='estimated'?'warn':''}">${r.servings} raciones</span></div><h3>${esc(r.name)}</h3><p>${title(r.category)}</p><div class="recipe-meta"><span>◷ ${r.active_time_minutes} min activos</span><span>⌛ ${r.total_time_minutes} total</span></div><div class="tag-row">${r.tags.slice(0,3).map(t=>`<span class="badge">${esc(t)}</span>`).join('')}</div><button class="btn secondary" data-action="recipe-detail" data-recipe="${r.id}">Ver receta</button></article>`}

function renderInventory(){const cats=['todas','despensa','nevera','congelador','frutas','verduras','carnes','pescados','lácteos','huevos','conservas','comida_preparada'],items=state.inventory.filter(i=>filters.inventory==='todas'||i.location===filters.inventory||ingredient(i.ingredient_id)?.category===filters.inventory);return `${head('Existencias domésticas','Inventario','Cantidades, mínimos y ubicación. Las compras marcadas se incorporan aquí.')}<div class="location-tabs">${cats.map(c=>`<button class="tab-btn ${filters.inventory===c?'active':''}" data-action="inventory-filter" data-filter="${c}">${title(c)}</button>`).join('')}</div><div class="table-wrap"><table><thead><tr><th>Producto</th><th>Cantidad</th><th>Ubicación</th><th>Mínimo</th><th>Estado</th><th></th></tr></thead><tbody>${items.map(inventoryRow).join('')}</tbody></table></div>`}
function inventoryRow(i){const ing=ingredient(i.ingredient_id),low=Number(i.quantity)<=Number(i.minimum_stock);return `<tr><td><strong>${esc(ing?.name)}</strong><div class="mono muted">${i.ingredient_id}</div></td><td><span class="stock-amount ${low?'stock-low':''}">${i.quantity} ${esc(i.unit)}</span></td><td>${title(i.location)}</td><td>${i.minimum_stock} ${esc(i.unit)}</td><td><span class="badge ${low?'danger':''}">${low?'reponer':'correcto'}</span></td><td><button class="btn danger small" data-action="empty-stock" data-inventory="${i.id}">Agotado</button></td></tr>`}

function renderCold(){const prepared=priorityFoods(),cold=state.inventory.filter(i=>['nevera','congelador'].includes(i.location));return `${head('Conservación','Nevera y congelador','Primero se muestran las preparaciones con consumo objetivo más próximo.')}<div class="grid grid-2"><section><div class="section-title"><h2>Consumir primero</h2></div><article class="card"><div class="priority-list">${prepared.length?prepared.map(f=>`${foodRow(f)}<div style="display:flex;gap:8px;justify-content:flex-end"><button class="btn small" data-action="consume-food" data-food="${f.id}">Consumir 1 ración</button><button class="btn ghost small" data-action="freeze-food" data-food="${f.id}">${f.location==='congelador'?'Pasar a nevera':'Congelar'}</button></div>`).join(''):'<div class="empty">No hay preparaciones pendientes.</div>'}</div></article></section><section><div class="section-title"><h2>Materia prima en frío</h2></div><article class="card"><div class="priority-list">${cold.map(i=>`<div class="priority-item"><span class="action-icon">${i.location==='congelador'?'❄':'▣'}</span><div class="grow"><strong>${esc(ingredient(i.ingredient_id)?.name)}</strong><span>${i.quantity} ${i.unit} · ${i.location}</span></div></div>`).join('')}</div></article></section></div>`}

function currentProducts(){return db.products.map(p=>({...p,...state.price_overrides[p.product_id]}))}
function productFor(ingredientId){return currentProducts().find(p=>p.ingredient_id===ingredientId)}
function normalizedPackage(p,unit){if(!p)return null;if(unit==='ud'||unit==='lata'||unit==='frasco'||unit==='paquete')return p.package_unit===unit?p.package_size:null;if(unit==='g')return p.package_unit==='kg'?p.package_size*1000:p.package_unit==='g'?p.package_size:null;if(unit==='ml')return p.package_unit==='l'?p.package_size*1000:p.package_unit==='ml'?p.package_size:null;return null}
function lineEstimate(item){const p=productFor(item.ingredient_id),size=normalizedPackage(p,item.unit);if(!p||!size)return {price:null,packages:null,product:p};const packages=Math.ceil(item.quantity/size);return {price:packages*p.current_price,packages,product:p}}
function planEstimate(plan){return plan.items.reduce((s,i)=>s+(lineEstimate(i).price||0),0)}
function weekEstimate(week){return db.shopping.filter(p=>p.week===week).reduce((s,p)=>s+planEstimate(p),0)}
function nextShoppingPlan(){return db.shopping.find(p=>p.items.some(i=>!state.shopping_checks[i.id]))||db.shopping.at(-1)}
function shoppingProgress(p){return Math.round(p.items.filter(i=>state.shopping_checks[i.id]).length/p.items.length*100)}
function freshnessLabel(){const remote=state.last_remote_price_refresh;if(remote)return `Precios remotos · ${new Date(remote).toLocaleString('es-ES')}`;return `Últimos conocidos · ${new Date(db.productUpdated).toLocaleDateString('es-ES')}`}
function renderNextShopping(){const p=nextShoppingPlan();return `${head('Lista operativa','Próxima compra',p.label,`<button class="btn secondary" data-action="refresh-prices">↻ Actualizar precios</button>`)}<div class="shopping-summary"><article class="card soft-green price-hero"><span class="eyebrow">Estimación de esta compra</span><div class="total-price">${money(planEstimate(p))}</div><div class="price-freshness"><span class="sync-dot"></span>${freshnessLabel()}</div><p>Solo se suman productos con formato y precio enlazados. Los demás aparecen como “sin precio”.</p></article><article class="card"><span class="eyebrow">Semana ${p.week}</span><h2>${money(weekEstimate(p.week))}</h2><p>Total estimado de las compras de la semana.</p><div class="work-number" style="font-size:28px">${shoppingProgress(p)}<small>% listo</small></div></article></div>${priceProviderNotice()}${shoppingPlanCard(p,true)}${offerSuggestions()}`}
function priceProviderNotice(){return state.settings.remote_price_feed_url?'':`<div class="notice"><strong>Modo resiliente:</strong> se muestran los últimos precios conocidos. Ahorramás no publica una API de precios para navegadores con garantía de CORS; puedes conectar un feed JSON actualizado desde Configuración.</div>`}
function renderAllShopping(){return `${head('Seis hitos de compra','Todas las compras','Dos compras semanales: una principal y una reposición corta.')}<div class="grid grid-2">${db.shopping.map(p=>shoppingPlanCard(p,false)).join('')}</div>`}
function shoppingPlanCard(p,expanded){return `<article class="card shopping-plan"><div class="shopping-plan-head"><div><span class="eyebrow">Compra ${p.sequence} · ${shoppingProgress(p)}%</span><h2>${esc(p.label)}</h2><p>${esc(p.notes)}</p></div><span class="badge blue">${money(planEstimate(p))}</span></div><div class="check-list">${p.items.map((i,index)=>shoppingItem(i,p,index,expanded)).join('')}</div></article>`}
function shoppingItem(i,p,index,expanded){const est=lineEstimate(i),checked=!!state.shopping_checks[i.id];if(!expanded&&index>=8)return index===8?`<a class="btn ghost small" href="#/compra">Ver ${p.items.length-8} productos más</a>`:'';return `<label class="check-item ${checked?'checked':''}"><input type="checkbox" class="shopping-check" data-item="${i.id}" data-plan="${p.id}" ${checked?'checked':''}><span><span class="item-name">${i.quantity} ${esc(i.unit)} · ${esc(ingredient(i.ingredient_id)?.name)}</span><span class="item-detail">${i.conditional?'Solo si está bajo mínimo · ':''}${est.product?`${esc(est.product.brand)} · ${est.packages||'?'} envase(s)`:'Sin producto de referencia'}</span></span><span class="item-price">${est.price===null?'—':money(est.price)}<small>${est.product?`${money(est.product.current_price)}/env.`:'sin precio'}</small></span></label>`}
function offerSuggestions(){const needs=new Map();db.shopping.forEach(p=>p.items.forEach(i=>needs.set(i.ingredient_id,(needs.get(i.ingredient_id)||0)+(Number(i.quantity)||0))));const offers=currentProducts().filter(p=>p.promotion&&p.unit_price<=p.target_price*.85).map(p=>{const need=needs.get(p.ingredient_id)||0;return `<div class="priority-item"><span class="action-icon">↓</span><div class="grow"><strong>${esc(p.name)} está ${Math.round((1-p.unit_price/p.target_price)*100)}% bajo tu objetivo</strong><span>Necesidad prevista: ${need} · ${p.promotion}. Compra solo el formato utilizable.</span></div></div>`});return `<div class="section-title"><h2>Ofertas útiles</h2></div><article class="card"><div class="priority-list">${offers.length?offers.join(''):'<div class="empty">No hay ofertas verificadas por debajo del umbral del 15%.</div>'}</div></article>`}

function renderFlows(){return `${head('Menos trabajo, menos desperdicio','Aprovechamiento','Cada flecha explica qué se produce, dónde se reutiliza y por qué se cocina de más.')}<div class="flow-grid">${db.flows.map(f=>{const dest=f.to_recipe_id?recipe(f.to_recipe_id)?.name:byId('days',f.to_day_id)?.weekday;return `<article class="card flow-card"><div class="flow-node"><span class="recipe-code">ORIGEN</span><h3>${esc(recipe(f.from_recipe_id)?.name)}</h3></div><div class="flow-output">${esc(outputName(f.output_id))}</div><div class="flow-dest">→ ${esc(dest)}</div><p>${esc(f.reason)}</p></article>`}).join('')}</div>`}

function renderSettings(){return `${head('Preferencias y datos','Configuración','El estado se guarda solo en este navegador. Exporta copias periódicas para moverlo o recuperarlo.')}<div class="grid grid-2"><section class="card"><h2>Plan y precios</h2><div class="settings-form"><div class="field"><label for="start-date">Fecha de inicio del lunes 1</label><input id="start-date" type="date" value="${state.settings.plan_start_date}"></div><div class="field"><label for="postal-code">Código postal de tienda</label><input id="postal-code" inputmode="numeric" maxlength="5" value="${esc(state.settings.postal_code)}"><small>Se conserva para un futuro proveedor por tienda. Actual: 45122.</small></div><div class="field"><label for="feed-url">Feed remoto de precios (JSON)</label><input id="feed-url" type="url" placeholder="https://…/products.json" value="${esc(state.settings.remote_price_feed_url)}"><small>Debe permitir CORS y usar el mismo esquema de products.json.</small></div><label class="switch-row"><span><strong>Actualizar al abrir compras</strong><small>Usa el feed remoto si está configurado.</small></span><input id="auto-refresh" class="switch" type="checkbox" ${state.settings.auto_price_refresh?'checked':''}></label><button class="btn" data-action="save-settings">Guardar configuración</button></div></section><section class="card"><h2>Copias y restauración</h2><p>Incluye estados, inventario, sobras, compras y precios importados; los JSON iniciales siguen intactos.</p><div class="settings-form" style="margin-top:18px"><button class="btn" data-action="export">Exportar copia JSON</button><button class="btn secondary" data-action="import">Importar copia JSON</button><button class="btn danger" data-action="reset">Restaurar datos iniciales</button></div><div class="notice" style="margin-top:18px">Versión de esquema: <strong>${state.schema_version}</strong>. Los datos iniciales están en la carpeta <span class="mono">data/</span>.</div></section></div><div class="section-title"><h2>Perfiles y raciones</h2></div><div class="grid grid-3">${db.settings.profiles.map(p=>`<article class="card"><span class="eyebrow">${p.id}</span><h3>${p.name}</h3><p>Multiplicador base: <strong>×${p.portion_multiplier}</strong></p><p>Proteína orientativa: ${p.protein_grams_range.join('–')} g</p>${p.add_ons?`<div class="tag-row">${p.add_ons.map(a=>`<span class="badge">+${a.quantity}${a.unit} ${ingredient(a.ingredient_id)?.name}</span>`).join('')}</div>`:''}</article>`).join('')}</div>`}

function bindView(){
  app.querySelectorAll('[data-action]').forEach(el=>el.addEventListener('click',handleAction));
  app.querySelectorAll('.meal-status').forEach(el=>el.addEventListener('change',changeMealStatus));
  app.querySelectorAll('.shopping-check').forEach(el=>el.addEventListener('change',toggleShopping));
  $('#recipe-search')?.addEventListener('input',e=>{filters.recipe=e.target.value;render()});
  $('#recipe-category')?.addEventListener('change',e=>{filters.category=e.target.value;render()});
}
function handleAction(e){const b=e.currentTarget,a=b.dataset.action;if(a==='recipe-detail')openRecipe(b.dataset.recipe);if(a==='edit-meal')openMeal(b.dataset.day,b.dataset.meal);if(a==='empty-stock'){state.inventory.find(i=>i.id===b.dataset.inventory).quantity=0;save();render()}if(a==='inventory-filter'){filters.inventory=b.dataset.filter;render()}if(a==='consume-food')consumeFood(b.dataset.food);if(a==='freeze-food')toggleFoodLocation(b.dataset.food);if(a==='refresh-prices')refreshRemotePrices(false);if(a==='save-settings')saveSettings();if(a==='export')exportState();if(a==='import')$('#import-file').click();if(a==='reset')resetState();if(a==='print')window.print()}
function changeMealStatus(e){const id=e.target.dataset.meal,status=e.target.value,day=byId('days',e.target.dataset.day),meal=Object.values(day.meals).find(m=>m.id===id);state.meal_statuses[id]=status;if(status==='prepared')generateLeftovers(day,meal);if(status==='consumed')consumeDayLeftovers(day);save();render()}
function generateLeftovers(day,meal){for(const rid of effectiveRecipeIds(meal)){const r=recipe(rid);for(const o of r?.leftover_outputs||[]){if(state.prepared_food.some(f=>f.output_id===o.output_id&&f.source_meal_id===meal.id))continue;const prep=dateForDay(day),target=new Date(prep);target.setDate(target.getDate()+(o.location==='congelador'?14:Math.min(r.storage_days||3,3)));state.prepared_food.push({id:`food_${o.output_id}_${Date.now()}`,output_id:o.output_id,name:o.name,source_recipe_id:r.id,source_meal_id:meal.id,prepared_date:prep.toISOString().slice(0,10),remaining_servings:o.servings||1,quantity:o.quantity||null,unit:o.unit||null,location:o.location||'nevera',target_consumption_date:target.toISOString().slice(0,10)})}}
}
function consumeDayLeftovers(day){for(const oid of day.leftover_consumptions){const f=state.prepared_food.find(x=>x.output_id===oid&&x.remaining_servings>0);if(f)f.remaining_servings=Math.max(0,f.remaining_servings-1)}}
function consumeFood(id){const f=state.prepared_food.find(x=>x.id===id);if(f)f.remaining_servings=Math.max(0,f.remaining_servings-1);save();render()}
function toggleFoodLocation(id){const f=state.prepared_food.find(x=>x.id===id);if(f){f.location=f.location==='congelador'?'nevera':'congelador';const d=new Date();d.setDate(d.getDate()+(f.location==='congelador'?30:2));f.target_consumption_date=d.toISOString().slice(0,10)}save();render()}
function toggleShopping(e){const id=e.target.dataset.item,checked=e.target.checked;state.shopping_checks[id]=checked;if(checked&&!state.purchased_items.includes(id)){const plan=byId('shopping',e.target.dataset.plan),item=plan.items.find(i=>i.id===id);addInventory(item);state.purchased_items.push(id)}save();render()}
function addInventory(item){let inv=state.inventory.find(i=>i.ingredient_id===item.ingredient_id&&i.unit===item.unit);if(inv)inv.quantity=Number(inv.quantity)+Number(item.quantity);else state.inventory.push({id:`inventory_user_${Date.now()}`,ingredient_id:item.ingredient_id,quantity:item.quantity,unit:item.unit,purchase_date:new Date().toISOString().slice(0,10),opened_date:null,best_before_date:null,location:ingredient(item.ingredient_id)?.category==='despensa'?'despensa':'nevera',minimum_stock:0,cost:lineEstimate(item).price,batch:null})}

function openRecipe(id){const r=recipe(id),scale=1;const d=$('#meal-dialog');d.innerHTML=`<div class="dialog-body"><div class="dialog-head"><div><span class="eyebrow">${r.source_code} · ${title(r.category)}</span><h2>${esc(r.name)}</h2><p>${r.servings} raciones · ${r.active_time_minutes} min activos · ${r.total_time_minutes} min total</p></div><button class="dialog-close" data-close aria-label="Cerrar">×</button></div><h3>Ingredientes</h3><div class="ingredient-list">${r.ingredients.map(i=>`<div class="ingredient-row"><span>${esc(ingredient(i.ingredient_id)?.name)}${i.optional?' <span class="badge">opcional</span>':''}</span><strong>${i.quantity*scale} ${esc(i.unit)}</strong></div>`).join('')}</div><h3>Preparación</h3><div class="steps">${r.steps.map(s=>`<div class="step">${esc(s)}</div>`).join('')}</div>${r.notes?`<div class="notice" style="margin-top:18px">${esc(r.notes)}</div>`:''}</div>`;d.querySelector('[data-close]').onclick=()=>d.close();d.showModal()}
function openMeal(dayId,mealId){const day=byId('days',dayId),meal=Object.values(day.meals).find(m=>m.id===mealId),current=effectiveRecipeIds(meal)[0],r=recipe(current),alts=[...(r?.possible_substitutions||[]),...fallbackRecipes(r)].filter((x,i,a)=>x!==current&&a.indexOf(x)===i).slice(0,8);const d=$('#meal-dialog');d.innerHTML=`<form class="dialog-body" method="dialog"><div class="dialog-head"><div><span class="eyebrow">${day.weekday} · ${meal.label}</span><h2>${esc(mealName(meal))}</h2><p>${meal.servings} raciones previstas</p></div><button class="dialog-close" value="cancel" aria-label="Cerrar">×</button></div><div class="field" style="margin-top:20px"><label for="replacement">Sustituir por</label><select id="replacement" class="search" style="width:100%"><option value="">Mantener el plan</option>${alts.map(id=>`<option value="${id}">${esc(recipe(id)?.name)}</option>`).join('')}<option value="improvised">Comida improvisada</option><option value="leftovers">Usar restos disponibles</option><option value="frozen">Usar comida congelada</option></select><small>Las primeras alternativas comparten categoría o están previstas por la documentación.</small></div><div class="grid grid-2" style="margin-top:18px"><button class="btn secondary" value="cancel">Cancelar</button><button class="btn" id="apply-replacement" type="button">Aplicar cambio</button></div></form>`;d.querySelector('#apply-replacement').onclick=()=>{const v=d.querySelector('#replacement').value;if(!v){delete state.meal_replacements[meal.id]}else if(v.startsWith('recipe_'))state.meal_replacements[meal.id]={recipe_ids:[v],label:recipe(v).name,type:'recipe'};else state.meal_replacements[meal.id]={recipe_ids:[],label:{improvised:'Comida improvisada',leftovers:'Restos disponibles',frozen:'Comida congelada'}[v],type:v};state.meal_statuses[meal.id]=v?'substituted':'pending';save();d.close();render()};d.showModal()}
function fallbackRecipes(r){if(!r)return[];return db.recipes.filter(x=>x.category===r.category&&x.id!==r.id).sort((a,b)=>sharedIngredients(b,r)-sharedIngredients(a,r)).slice(0,5).map(x=>x.id)}
function sharedIngredients(a,b){const ids=new Set(a.ingredients.map(i=>i.ingredient_id));return b.ingredients.filter(i=>ids.has(i.ingredient_id)).length}

async function refreshRemotePrices(silent){const url=state.settings.remote_price_feed_url;if(!url){if(!silent)toast('Configura un feed remoto en Configuración');return}try{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.json(),items=data.products||data;if(!Array.isArray(items))throw new Error('Formato no válido');for(const p of items){if(!p.product_id||p.current_price==null)continue;state.price_overrides[p.product_id]={current_price:p.current_price,unit_price:p.unit_price,price_date:p.price_date||new Date().toISOString().slice(0,10),price_status:'current',promotion:p.promotion||null,promotion_end_date:p.promotion_end_date||null}}state.last_remote_price_refresh=new Date().toISOString();save(false);if(!silent)toast(`${items.length} precios actualizados`);render()}catch(err){if(!silent)toast(`No se pudo actualizar: ${err.message}`)}}
function saveSettings(){state.settings.plan_start_date=$('#start-date').value;state.settings.postal_code=$('#postal-code').value.trim();state.settings.remote_price_feed_url=$('#feed-url').value.trim();state.settings.auto_price_refresh=$('#auto-refresh').checked;save();render()}
function exportState(){const blob=new Blob([JSON.stringify({app:'mesa21',exported_at:new Date().toISOString(),state},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`mesa21-copia-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Copia exportada')}
async function importState(e){const file=e.target.files?.[0];if(!file)return;try{const parsed=JSON.parse(await file.text()),candidate=parsed.state||parsed;if(!candidate.inventory||!candidate.settings)throw new Error('No parece una copia de Mesa 21');state=candidate;migrateState();save();render();toast('Copia importada')}catch(err){toast(`Importación fallida: ${err.message}`)}e.target.value=''}
function resetState(){if(!confirm('¿Restaurar el estado inicial? Se borrarán tus cambios locales.'))return;state=initialState();save();render()}

if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
init();
